apiVersion: v1
kind: Service
metadata:
  labels:
    app: ne-pcrf
  name: ne-pcrf
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: ne-pcrf
    port: 3868
    protocol: TCP
    targetPort: 3868
  - name: ne-pcrf-secure
    port: 5868
    protocol: TCP
    targetPort: 5868
  selector:
    app: ne-pcrf
