apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ne-mgo
spec:
  serviceName: ne-mgo
  selector:
    matchLabels:
      app: ne-mgo
  replicas: 1
  template:
    metadata:
      labels:
        app: ne-mgo
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: mongodb
        image: mongo:4.2.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: mongo_initdb_database
