apiVersion: v1
kind: ConfigMap
metadata:
  name: ne-mme-config
data:
  nw_s1ap_ip: "172.16.0.10"
  nw_gtpc_ip: "172.17.0.10"
  nw_sgw_gtpc_ip: "172.17.0.11"
  nw_pgw_gtpc_ip: "172.17.0.12"
  mcc: "901"
  mnc: "70"
  tac: "1"
  mme_gid: "2"
  mnc_code: "1"
  nw_name: "NextEPC"
