apiVersion: v1
kind: Service
metadata:
  labels:
    app: ne-mme
  name: ne-mme
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: ne-mme
    port: 3868
    protocol: TCP
    targetPort: 3868
  - name: ne-mme-secure
    port: 5868
    protocol: TCP
    targetPort: 5868
  - name: ne-mme-s11-gtpc
    port: 2123
    protocol: UDP
    targetPort: 2123
# if enabled SCTPSupport in kube-apiserver, SCTP Protocol is available
# Kubeadm Setup Example:
#   apiServerExtraArgs:
#     feature-gates: SCTPSupport=true
#  - name: s1ap
#    port: 36412
#    protocol: SCTP
#    targetPort: 36412
  selector:
    app: ne-mme
