resources:
 - 00_mme-sa.yaml
 - 01_mme-rbac.yaml
 - 02_mme-configmap.yaml
 - 03_mme-service.yaml
 - 04_mme-multus.yaml
 - 05_mme-deployment.yaml


namespace: lte

secretGenerator:
- name: ne-mme-tls-secret
  namespace: default
  files:
  - certs/mme.cacert.pem
  - certs/mme.cert.pem
  - certs/mme.key.pem
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
